BC-6585-Setup DB tests for BKG
hpi-schul-cloud/authorization-service pull request #2
Opened 2024-03-05 17:18 UTC by VikDavydiuk

# Description

## Links to Tickets or other pull requests

- https://ticketsystem.dbildungscloud.de/browse/BC-6585

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-07 11:34 UTC, EzzatOmar requested changes
There are two errors in the test run.

`db_1              | 2024-03-07 11:31:50.906 UTC [37] ERROR:  syntax error at or near ";" at character 38

db_1              | 2024-03-07 11:31:50.906 UTC [37] STATEMENT:  DROP FUNCTION IF EXISTS col_is_null (;`

You might want to check them.

I left a few comments. Once they are fixed we can merge the code.

2024-03-07 11:34 UTC, EzzatOmar commented on Dockerfile
It looks like you do not seed the postgres pgtap with our seed data.

2024-03-07 11:34 UTC, EzzatOmar commented on docker-compose.local.yml
Move the pgtap out of docker-compose.local.yml.
Create a new file docker-compose.test.yml.

We want to separate the dev and test environments.

2024-03-07 11:34 UTC, EzzatOmar commented on test/test_pgtap.sql
Add a new file to test if the tables in db/seed/tables are present.

2024-03-07 12:16 UTC, EzzatOmar commented
Can you update the README.md there is an error.

```docker-compose up -f ./docker-compose.local.yml```
->
```docker-compose -f ./docker-compose.local.yml up```

2024-03-07 12:29 UTC, EzzatOmar commented
Why are we using PGTAP_VERSION=v1.1.0?

There is v1.3.2 published.

https://github.com/theory/pgtap/releases/tag/v1.3.2

2024-03-11 11:04 UTC, mamutmk5 requested changes
What even wan't you to test with this?
That the db is as you think it shoud be after creatin?

2024-03-11 11:04 UTC, mamutmk5 commented on Dockerfile
> +    TESTS="/test/*.sql"
No, no passwords in thsi files, even for testing not.

2024-03-11 11:04 UTC, mamutmk5 commented on Dockerfile
> +    && make
make every thing to one run command, It's not nessesery to make it over multibel lines.

2024-03-11 11:04 UTC, mamutmk5 commented on Dockerfile
> +    && make
missing the make install and make clean things.
we don't want to have build artefacts in the Image

2024-03-11 11:04 UTC, mamutmk5 commented on Dockerfile
> +    && tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz \
Where do you use dockerize in this container?

2024-03-11 11:04 UTC, mamutmk5 commented on Dockerfile
Remane the File the Dockerfile shoud generate the APP not an contaienr for test.
Then add Pipliens who build your test containers and run the test in the github pipelines.

2024-03-12 12:07 UTC, blazejpass commented on Dockerfile
> +    TESTS="/test/*.sql"
removed those envs from this file

2024-03-12 12:07 UTC, blazejpass commented on Dockerfile
> +    && make
run commands were merged

2024-03-12 13:04 UTC, mamutmk5 commented on Dockerfile
> +    && cd pgtap && git checkout tags/$PGTAP_VERSION \
Missing new line
```suggestion
    && cd pgtap \
    && git checkout tags/$PGTAP_VERSION \
```

2024-03-12 13:04 UTC, mamutmk5 commented on README.md
> +asd
```suggestion
pgTest run Local
```bash
docker build -t postgres-pgtap:16.1 -f Dockerfile.test .
docker run -d --rm --name pgtap-tests -v "./db/seed:/docker-entrypoint-initdb.d" -e "POSTGRES_PASSWORD=example" -e "POSTGRES_USER=postgres"\
  -e "DATABASE=postgres"  -e "HOST=localhost"  -e "TESTS=/test/*.sql"  -e "PORT=5432" postgres-pgtap:16.1
docker exec pgtap-tests /test/test.sh
docker stop pgtap-tests
```
```

2024-03-14 10:30 UTC, bn-pass requested changes
Just some small optimization, looks good to me overall.

2024-03-14 10:30 UTC, bn-pass commented on Dockerfile.test
> +COPY run-pg-and-pgtap-test.sh /test/run-pg-and-pgtap-test.sh
Could you please try the following? Always two image layers less 😊 
```suggestion
COPY run-pg-and-pgtap-test.sh test/test.sh test/unit/*.sql /test/
COPY db/seed/*.sql /seed/
```

2024-03-14 10:30 UTC, bn-pass commented on README.md
> +-e DATABASE="postgres" postgres-pgtap:16.1
I'd suggest linking the file like so:
```
[run-test.sh](run-test.sh)
```
instead of copying its content here - usually no one remembers to update copies like that after changing the original file :) (or are not aware its content is copied somewhere).

2024-03-14 10:30 UTC, bn-pass commented on docker-compose.test.yml
@blazejpass has this file been updated by you after the recent changes? If not did you try to run it? Please delete it if it no longer works or is not needed anymore - always better to have less things (especially not used ones 🙂) to maintain.

2024-03-14 11:21 UTC, bn-pass requested changes

2024-03-14 11:21 UTC, bn-pass commented on Dockerfile.test
> +ENV DOCKERIZE_VERSION=v0.6.1
@blazejpass I think you don't need it anymore as you've got rid of the `dockrize` right?

2024-03-14 11:23 UTC, bn-pass approved these changes

2024-03-18 09:07 UTC, EzzatOmar commented
After discussions with other team members I decided to not merge the pgtap PR and pivot to just use jest.
We will still write the same tests but instead in plain SQL we will just typescript + SQL.
The rational is that the adoption within the team is not so great using SQL.
Familiarity is more important than less complexity in our tests.

2024-03-18 09:07 UTC, closed without merging